@startuml
 
 
class GeneratorDebug {
 + lrGeneratorDebug()
 + lalrGeneratorDebug()
 + generatorDebug()
 + lookaheadDebug()
 } 
Jison -> GeneratorDebug : uses
Jison -> GeneratorDebug : uses
Jison -> GeneratorDebug : uses
Jison -> GeneratorDebug : uses
 
@enduml
