@startuml nonterminal

!theme plain

class Nonterminal {
    +symbol: String
    +productions: Set
    +first: Array<String>
    +follows: Array<String>
    +nullable: Boolean
    +toString(): String
}

Nonterminal --> Set : uses
Nonterminal --> typal : uses

@enduml
