@startuml parser

!theme plain

class Parser {
    +trace(): void
    +warn(): void
    +error(msg: String): void
    +parseError(str: String, hash: Object): void
    +parse(input: String): Boolean
    +init(dict: Object): void
}

Parser --> typal : extends
 
Parser --> Set : uses

@enduml
