@startuml production

!theme plain

class Production {
    +symbol: String
    +handle: Array
    +nullable: Boolean
    +id: String
    +first: Array
    +precedence: Number
    +constructor(symbol: String, handle: Array, id: String)
    +toString(): String
}

Production --> typal : extends

@enduml
