@startuml conflict_resolver

!theme plain

class TableGenerator {
    +findDefaults(states: Array): Object
    +resolveConflict(production: Object, op: Object, reduce: Array, shift: Array): Object
}


@enduml
