@startuml LR0GeneratorModule

!theme plain

class LR0Generator {
    - type: String
    + constructor()
    + afterconstructor(): void
}
 
LR0Generator --|> Generator
LR0Generator --> LookaheadMixin
LR0Generator --> LRGeneratorMixin

@enduml
