@startuml SLRGeneratorModule

!theme plain

class SLRGenerator {
    - type: String
    + lookAheads(state: ItemSet, item: Item): Array
    + afterconstructor(): void
}


SLRGenerator --|> Generator
SLRGenerator --> LookaheadMixin
SLRGenerator --> LRGeneratorMixin

@enduml
