@startuml 

!theme plain

class LookaheadMixin {
    +computeLookaheads(): void
    +followSets(): void
    +first(symbol: string|Array): Array
    +firstSets(): void
    +nullableSets(): void
    +nullable(symbol: string|Array): boolean
}

LookaheadMixin --> "Set": uses
LookaheadMixin --> "productions": uses
LookaheadMixin --> "nonterminals": uses

@enduml
