@startuml set_functions

!theme plain

class lookaheaddebug {
    +beforenullableSets(): void
    +beforefirstSets(): void
    +beforefollowSets(): void
    +afterfollowSets(): void
}

lookaheaddebug --> "nonterminals": uses

@enduml
